import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
@Component({selector:'app-reservation',standalone:true,imports:[FormsModule],template:`
<section id="reservas" class="reservation section"><div class="reserve-copy reveal"><span class="eyebrow">TU MESA TE ESPERA</span><h2>Reserva una noche<br><em>inolvidable</em></h2><p>Déjanos tus datos y nos pondremos en contacto para confirmar todos los detalles.</p><div class="contact-mini"><b>Reservas directas</b><a href="tel:+51999999999">+51 999 999 999</a><span>Lun–Dom · 12:00 pm en adelante</span></div></div>
<form (ngSubmit)="submit()" class="reveal" #form="ngForm">
 @if(sent()){<div class="success"><b>¡Reserva recibida!</b><p>Nos pondremos en contacto contigo para confirmarla.</p><button type="button" (click)="sent.set(false)">Nueva reserva</button></div>} @else {
 <label>Nombre<input name="name" ngModel required placeholder="Tu nombre completo"></label><label>Teléfono<input name="phone" ngModel required placeholder="+51 999 999 999"></label><label>Correo<input name="email" type="email" ngModel required placeholder="tu@correo.com"></label><label>Personas<select name="people" ngModel required><option value="" disabled selected>Selecciona</option><option>2 personas</option><option>3 personas</option><option>4 personas</option><option>5+ personas</option></select></label><label>Fecha<input name="date" type="date" ngModel required></label><label>Hora<input name="time" type="time" ngModel required></label><label class="full">Mensaje adicional<textarea name="message" ngModel rows="3" placeholder="Alergias, ocasión especial..."></textarea></label><button class="gold-btn full" [disabled]="form.invalid">Confirmar reserva <span>→</span></button>}
</form></section>`,styles:[`
.reservation{display:grid;grid-template-columns:.85fr 1.15fr;gap:8vw;background:#101010}.reserve-copy{padding-top:2rem}.reserve-copy h2{color:white}.reserve-copy p{color:#aaa;max-width:480px}.contact-mini{margin-top:3rem;border-left:1px solid var(--gold);padding-left:1.5rem;display:grid;gap:.35rem}.contact-mini a{color:var(--gold);font:1.6rem Italiana}.contact-mini span{color:#888;font-size:.85rem}form{background:#171717;padding:2.4rem;border:1px solid #ffffff12;display:grid;grid-template-columns:1fr 1fr;gap:1.2rem;border-radius:1rem}label{display:grid;gap:.5rem;color:#bbb;font-size:.78rem;letter-spacing:.07em;text-transform:uppercase}.full{grid-column:1/-1}input,select,textarea{width:100%;padding:1rem;background:#0d0d0d;border:1px solid #333;border-radius:.5rem;color:white;font:inherit;outline:none}input:focus,select:focus,textarea:focus{border-color:var(--gold)}.success{grid-column:1/-1;text-align:center;padding:5rem 1rem}.success b{font:2.2rem Italiana;color:var(--gold)}.success p{color:#aaa}.success button{background:none;border:0;color:white;text-decoration:underline}@media(max-width:800px){.reservation{grid-template-columns:1fr}form{grid-template-columns:1fr;padding:1.35rem}.full{grid-column:auto}}
` ]}) export class ReservationComponent{sent=signal(false);submit(){this.sent.set(true)}}
